import react from 'react';
import { StyleSheet } from "react-native";

const Estilos = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#fff',
      alignItems: 'center',
      justifyContent: 'center',
    },
    logotipo:{
      width:300,
      height:300
    },
    botaoLoguin:{
      backgroundColor:'#e6e6e6',
      width:'50%',
      alignItems:'center',
      padding:5,
      margin:5,
      borderRadius:20
  },
  botaoText:{
    color:  '#999999'
  },
  checkBoxEstilo:{
    flexDirection:'row',
    alignItems:'center',
    margin:10
  },
  btnRecuperarSenha:{
    color:'#F2C029',
    fontWeight:'bold'
  },
  btnCriarNovoUsuario:{
    color:'#012362',
    fontWeight:'bold'
  },
  impuText:{
    borderWidth:5,
    borderColor:'#66A638',
    width:'80%',
    paddingLeft:12,
    borderRadius:50,
    marginTop:10
  },
  btnPromocoes:{
    width:'90%',
    borderRadius:20,
    margin:5
  },
  caixaTextBusca:{ 
    borderWidth:3,
    marginTop:10,
    width:'90%',
    borderColor:'#5AA637',
    borderRadius:30,
    flexDirection:'row'
  },
  listaProdutos:{ 
  borderRadius:9,
   backgroundColor: '#ffffff',
   padding:5,
   margin:5,  
  },
  imageProdutos:{
    height:150,
     width: 150
},
precoProdutos:{ 
  color:'#02296D',
  fontWeight:'bold',
  fontSize:19,
  margin:5},
  Lojacontainer: {
    flex: 1,
    backgroundColor: '#F5F5F5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerPersonalizado:{
    backgroundColor:'#66A638',
    width:'100%',
    height:100,
    borderBottomEndRadius:30,
    borderBottomStartRadius:30,
    flexDirection:'row',
    alignItems:'center'
  },
  nomeTitulo:{
    color:'#ffff',
    fontSize:20,
    fontWeight:'bold'

  },
  usuarioMinifoto:{ 
    width:50,
    height:50,
    borderRadius:50,
    marginLeft:'10%',
  },
  detalheBar:{
    flexDirection:'row',
    borderBottomWidth:StyleSheet.hairlineWidth,
  },
  definirQuantidade:{
    flexDirection:'row',
    alignItems:'center',
    margin:10
  },
  quantidadeBox:{
    width:100,
    borderWidth:3,
    borderColor:'#66A638',
    borderRadius:5,
    paddingLeft:10,
    margin:10
  },
  tituloProduto:{
    fontSize:25,
    margin:10,
    fontWeight:'bold'
  },
  indicador:{
    alignItems:'center',
    justifyContent:'center'
  },
  mostrarPreco:{
    color:'#02296D',
    fontWeight:'bold',
    fontSize:19,
    margin:5,
    right:'10%',
    position:'absolute'
  },
  localTexto:{
    color:'#999999',
    margin:10,
    fontSize:16,
    fontWeight:'bold'
  },
  lista:{
      flexDirection:'row',
      margin:9,
  },
  imageLista:{
      width:100,
      height:100
  },
  textoTotal:{
      margin:5,
  },
  valorText:{
      color:'#04C4D9',
      fontWeight:'bold',
      fontSize:20
     },
     txt:{
         margin:5,
     },
     boxTxt:{
         flexDirection:'column'
     },
     tituloItem:{
         fontSize:23,
         fontWeight:'bold',
         margin:5
     },
     btnPurcase:{
         backgroundColor:'#04C4D9',
         margin:9,
         width:150,
         borderRadius:50,
         alignItems:'center'
     },
     btDell:{
         position:'absolute',
         left:'90%',
         marginTop:10,
     },
     TituloCadatroProd:{
       fontSize:30,
       top:'-15%',
       color:'#66A638',
       fontWeight:'bold',
     },
     textoExplicativo:{
      fontSize:16,
      top:'-15%',
      color:'#66A638',
      fontWeight:'bold',
      margin:10,
      textAlign:'center'
     },
     caixaTextoProduto:{
      top:'-15%',
       borderBottomWidth:3,
       borderColor:'#66A638',
       width:300,
       height:30,
       paddingLeft:9,
     },
     btnConfirmaCadProd:{
      top:'-15%',
       flexDirection:'row',
       borderRadius:50,
       backgroundColor:'#66A638',
       padding:10
     },
     textoConfirBtnCadProd:{
       color:'#ffff',
       fontWeight:'bold'
     },
     textoExplicativoDois:{
      fontSize:16,
      top:'-15%',
      color:'#66A638',
      fontWeight:'bold',
      justifyContent:'flex-start',
      marginBottom:10
     },
     caixaImagem:{ 
       top:'-15%',
       borderWidth:3,
       borderColor:'#66A638',
       width:210,
       height:210,
       alignItems:'center',
       justifyContent:'center',
      },
      btnLimparFormulario:{
         top:'-15%',
         flexDirection:'row',
         borderRadius:50,
         backgroundColor:'#999999',
         padding:10,
         marginRight:10,
         width:125,
         alignItems:'center',
         justifyContent:'center'
       },
       btnAddNovoProd:{
         flexDirection:'row',
         backgroundColor:'#66A638',
         borderRadius:50,
         margin:10,
         padding:5
       },
       prodUsuario:{
         height:500,
         width:300,
        },
        gridItem:{
         padding:11,
         borderBottomColor:'black',
         flexDirection:'row',
         alignItems:'center',
         borderBottomWidth:StyleSheet.hairlineWidth,
        },
        textUsuarioProd:{
          color:'#3E4862',
          fontSize:16,
          fontWeight:'bold',
          margin:5
        },
        editarEdeletar:{
          left:'90%',
          position:'absolute'
        },
        separadorBtn:{
          margin:10,
          borderBottomWidth:StyleSheet.hairlineWidth,
          borderBottomColor:'black',
        },
        carrinho:{
          marginTop:'20%',
          position:'absolute',
          width:'100%',
          backgroundColor:'#ffff',
          height:'100%'
        },
        mensagems:{
          position:'absolute',
          width:'100%',
          backgroundColor:'#F4F4F8',
          height:'100%',
        },
        mensagem:{
          flexDirection:'row',
          backgroundColor:'#ffff',
          height:80,
          margin:10,
          alignItems:'center',
          borderBottomWidth:StyleSheet.hairlineWidth,
          borderBottomColor:'black',
        },
        tituloMensagem:{
          color:'#158C03',
          margin:5,
          fontSize:16,
          fontWeight:'bold',
          marginLeft:'10%'
        },
        barMensagem:{
        backgroundColor:'#ffff',
        height:45,
        alignItems:'center',
        flexDirection:'row',
        borderBottomWidth:StyleSheet.hairlineWidth,
        borderBottomColor:'black',
        },
        barBtnMsn:{
          margin:10
        },
        perfilFont:{
          fontSize:100,
          color:'#66A638'
        },
        perfilCirculo:{
          borderWidth:9,
          borderRadius:100,
          width:150,
          height:150,
          alignItems:'center',
          alignContent:'center',
          borderColor:'#66A638',
          left:'25%',
        }, 
        usuariMinicirculo:{ 
          width:50,
          height:50,
          borderRadius:50,
          borderWidth:3,
          margin:10,
          alignItems:'center',
          justifyContent:'center',
          borderColor:'#ffff'
        },
        perfilMinefont:{
          color:'#ffff',
          fontSize:30,
          fontWeight:'bold',
          top:'-5%',
          position:'absolute'
        }, 
        usuariMinicirculoDrawer:{ 
          width:50,
          height:50,
          borderRadius:50,
          borderWidth:3,
          margin:10,
          alignItems:'center',
          justifyContent:'center',
          borderColor:'#66A638'
        },
        perfilMinefontDrawer:{
          color:'#66A638',
          fontSize:20,
          fontWeight:'bold'
        },
        notifica:{
          backgroundColor:'#F2B035',
          borderRadius:100,
          alignItems:'center',
          alignContent:'center',
          height:20,
          width:20,
          left:'55%',
          bottom:'20%',
          position:'absolute'
        },
        sinoEstilo:{
          position:'absolute',
          marginTop:'-7%',
          left:'80%'
        },
        btnEsvaziarSacola:{
        backgroundColor:'#D90404',
        alignItems:'center',
        justifyContent:'center',
        padding:10,
        borderRadius:50,
        left:'90%',
        position:'absolute',
        bottom:'5%',
        margin:20
      },
      menuUsuario:{
        backgroundColor:'#999999',
        flex:1
      },
      usuarioImfo:{
        backgroundColor:'#ffff',
        margin:20,
        borderRadius:20,
        paddingTop:10,
        height:500
      },
      editarIfo:{
        flexDirection:'row',
        marginTop:20,
        alignItems:'baseline',
        borderBottomWidth:StyleSheet.hairlineWidth,
        borderBottomColor:'black',
        width:'85%',
        marginStart:10
      },
      fontInfoEstilo:{
        color:'#66A638',
        fontSize:15,
        fontWeight:'bold',
        marginLeft:5
      },
      btnEdInfo:{
        left:'100%',
        bottom:1,
        position:'absolute'
      },
      imputTextCad:{
        borderWidth:5,
        borderColor:'#66A638',
        width:'80%',
        paddingLeft:12,
        borderRadius:50,
        flexDirection:'row',
        marginBottom:20,
        top:'-10%'
      },
      CompararSenha:{
        color:'#D90404',
      }
  });

 export default Estilos


  